## Лабораторная работа на тему: "Анализ DNS-серверов"

### Цель работы:  
Проанализировать сетевые параметры 4-х DNS-серверов.

### Исходные данные:  
ОC Linux Mint 19.3 Tricia, whois, traceroute, ping

### Варианты решения задачи  

#### Вариант 1:  
1. Сделать анализ на Linux-системе при помощи утилиты traceroute

#### Вариант 2:  
2. Сделать анализ на Windows сисетме при помощи tracert

### Общий план выполнения:  
1) Проверить доступность DNS-сервера при помощи команды ping
2) Использовать 2ip для просмотра данных о каждом промежуточном узле.
3) Исселодвать движение траффика до конечного узла при помощи traceroute

Данные действия необходимо повторить для следующих 4 целей:
- Google Public DNS  
- Cloudflare DNS  
- OpenDNS  
- DNS провайдера (OTS)

### Содержание ЛР:  
1) Google Public DNS - 8.8.8.8  
Доступность DNS-сервера:
```{bash} 
ping -c 5 8.8.8.8
```

Результат tracerout'a:
```{bash} 
traceroute -I --resolve-hostnames 8.8.8.8
```

#### Информационная таблица:
| № |Первый ping|Второй ping|Третий ping|Узел|Месторасположение| Организация| Средняя RTT|
|:-:|:---------:|:---------:|:---------:|:--:|:---------------:|:----------:|:----------:|
| 1| 0.459 ms | 0.532 ms | 0.285 ms | 10.0.2.2                                         |МО|_gateway|0.438|
| 2| 2.023 ms | 1.674 ms | 1.828 ms |  192.168.0.1                                           |МО| Адресс маршрутизатора |1.841|
| 3| 6.354 ms| 3.430 ms| 4.435 ms|  10.228.19.254       |МО| Gray IP |4.738|
| 4| 4.318 ms | 4.306 ms| 4.150 ms|  10.228.100.1 |МО| Gray IP |4.258|
| 5| 4.687 ms | 4.064 ms| 4.298 ms|  31.129.192.61 (core-v276-len2.nat1.ots-net.ru)      |МО|ООО ОТС|4.258|
| 6| 4.519 ms | 4.205 ms| 4.316 ms|  31.129.192.110 (zapret.ots-net.ru)    |МО|ООО ОТС|4.347|
| 7| 4.751 ms| 3.986 ms| 4.056 ms|  31.129.192.105 (c65k.border.ots-net.ru)   |МО|ООО ОТС|4.229|
| 8| *    | *   | *   |  Request timed out.|
| 9| *    | *   | *   |  Request timed out.|
| 10| 22.818 ms | 20.839 ms | 17.140 ms |  188.43.30.42 (Filter-gw.transtelecom.net) |Москва|TransTeleCom|20.266|
| 11| 17.836 ms    | 20.468 ms   | 16.780 ms |  188.43.245.41 (BL-Servers-NNovgorod-gw.transtelecom.net) |Москва|TransTeleCom|18.361|
| 12|*    | *   | *   |  Request timed out.|
| 13| 30.360 ms   | 31.971 ms  | 24.405 ms |  217.150.44.9 (Google-gw.transtelecom.net) |Тулун|Transtelecom p-t-p interfaces|28.912|
| 14| 17.894 ms | 18.238 ms   | 16.996 ms |  108.170.250.34 |Mountain View|Google LLC|17.709|
| 15| 29.681 ms   | 31.094 ms | 34.755 ms |  216.239.50.46 | Not Stated |Google LLC|31.843|
| 16| 31.901 ms   | 32.116 ms   | 29.435 ms |  72.14.238.168 | Mountain View|Google LLC|31.150|
| 17| 29.292 ms    | 30.635 ms   | 29.628 ms  |  216.239.62.13 | Not Stated |Google LLC|29.851|
| 18|*    | *   | *   |  Request timed out.|
| 19|*    | *   | *   |  Request timed out.|
| 20|*    | *   | *   |  Request timed out.|
| 21|*    | *   | *   |  Request timed out.|
| 22|*    | *   | *   |  Request timed out.|
| 23|*    | *   | *   |  Request timed out.|
| 24|*    | *   | *   |  Request timed out.|
| 25|*    | *   | *   |  Request timed out.|
| 26|*    | *   | *   |  Request timed out.|
| 27|*    | *   | *   |  Request timed out.|
| 28|*    | *   | *   |  Request timed out.|
| 29|32.768 ms| 28.719 ms|30.110 ms|  8.8.8.8 (dns.google)|New York|Google LLC|30.532|


2) Cloudflare DNS - 1.1.1.1  
Доступность DNS-сервера:
```{bash} 
ping -c 5 1.1.1.1
```

Результат tracerout'a:
```{bash} 
traceroute -I --resolve-hostnames 1.1.1.1
```

#### Информационная таблица:
| № |Первый ping|Второй ping|Третий ping|Узел|Месторасположение| Организация| Средняя RTT|
|:-:|:---------:|:---------:|:---------:|:--:|:---------------:|:----------:|:----------:|
|  1| 0.442 ms| 0,443 ms  | 0.288 ms | 10.0.2.2 (_gateway) |МО|_gateway|0.391|
|  2| 1.951 ms| 2.101 ms  | 1.966 ms | 192.168.0.1 |МО| Адрес маршрутизатора |2.006|
|  3| 3.922 ms| 8.210 ms  | 4.478 ms | 10.228.19.254 |МО| Gray IP |5.56|
|  4| 7.844 ms| 6.109 ms  | 4.574 ms | 10.228.100.1 | МО| Gray IP |6.17|
|  5| 3.797 ms| 3.831 ms  | 4.056 ms | 31.129.192.61 (core-v276-len2.nat1.ots-net.ru) |МО|ООО ОТС|3.895|
|  6| 4.047 ms| 4.660 ms  | 3.998 ms | 31.129.192.110 (zapret.ots-net.ru) |МО|ООО ОТС|4.235|
|  7| 4.185 ms| 4.517 ms  | 4.567 ms | 31.129.192.105 (c65k.border.ots-net.ru) |МО|ООО ОТС|4.233|
|  8| 6.437 ms| 4.674 ms  | 8.522 ms | 89.222.201.49 (207-vl.rt1.msk1.netorn.net) |Москва|NETORN infrastructure p2p connections|6.544|
|  9| 15.496 ms| 25.843 ms  | 25.911 ms | 195.208.209.7 (msk-ix.cloudflare.com) |Москва|Joint-stock company "Internet Exchange "MSK-IX|33.625|
|  10| 10.056 ms| 6.009 ms  | 8.928 ms | 1.1.1.1 (one.one.one.one)|Australia, Research|APNIC and Cloudflare DNS Resolver project|8.331|


3) OpenDNS - 208.67.222.222  
Доступность DNS-сервера:
```{bash} 
ping -c 5 208.67.222.222
```

Результат tracerout'a:
```{bash} 
traceroute -I --resolve-hostnames 208.67.222.222
```


#### Информационная таблица:
| № |Первый ping|Второй ping|Третий ping|Узел|Месторасположение| Организация| Средняя RTT|
|:-:|:---------:|:---------:|:---------:|:--:|:---------------:|:----------:|:----------:|
|  1| 0.427 ms  | 0.273 ms  | 0.454 ms  | 10.0.2.2 (_gateway) |МО|_gateway|0.385|
|  2| 2.226 ms  | 2.840 ms  | 1.741 ms  | 192.168.0.1   |МО|Адрес маршрутизатора|2.269|
|  3| 4.964 ms  | 8.688 ms  | 7.533 ms  | 10.228.19.254  |МО| Gray IP |7.061|
|  4| 7.910 ms  | 6.833 ms  | 3.815 ms  | 10.228.100.1 |МО| Gray IP |6.186|
|  5| 4.020 ms  | 5.782 ms  | 4.049 ms  | 31.129.192.61 (core-v276-len2.nat1.ots-net.ru) |МО| ООО ОТС |4.617|
|  6| 4.464 ms | 5.5 ms | 4.581 ms | 31.129.192.245 (border-v625-len2.nat1.ots-net.ru) |МО|ООО ОТС|4.848|
|  7| 5.396 ms | 4.929 ms | 3.757 ms | 89.222.201.49 (207-vl.rt1.msk1.netorn.net) |Москва|NETORN infrastructure p2p connections|4.694|
|  8| 4.572 ms | 7.645 ms | 9.361 ms | 77.94.162.129 |Москва|Nauka-Svyaz|7.193|
|  9| 9.542 ms | 10.519 ms| 7.677 ms | 77.94.160.74  |Москва|Nauka-Svyaz|9.246|
| 10| 10.314 ms| 10.327 ms| 8.149 ms | 37.29.16.69 |Самара|Volga Branch of OJSC MegaFon NOC|9.597|
| 11| 44.675 ms| 44.308 ms| 39.933 ms| 83.169.204.118 |Самара|Volga Branch of OJSC MegaFon NOC|42.972|
| 12| 44.408 ms| 55.311 ms| 39.943 ms| 83.169.204.126 |Самара|Volga Branch of OJSC MegaFon NOC |46.554|
| 13| 44.416 ms| 44.868 ms| 48.540 ms| 80.81.194.218 (rtr1.fra.opendns.com)  |Frankfurt|ORG-DtGI1-RIPE|45.941|
| 14| 48.158 ms| 45.267 ms| 44.875 ms| 208.67.222.222 (resolver1.opendns.com)|San Francisco |Cisco OpenDNS, LLC |46.1|


4) OTS - 91.214.71.124  
Доступность DNS-сервера:
```{bash} 
ping -c 5 31.129.193.2
```

Результат tracerout'a:
```{bash} 
traceroute -I --resolve-hostnames 31.129.193.2
```

#### Информационная таблица:
| № |Первый ping|Второй ping|Третий ping|Узел|Месторасположение| Организация| Средняя RTT|
|:-:|:---------:|:---------:|:---------:|:--:|:---------------:|:----------:|:----------:|
|  1| 0.343 ms| 0.408 ms| 0.209 ms| 10.0.2.2 (_gateway)  |МО|_gateway|0.32|
|  2| 3 ms| 3.396 ms| 1.84 ms|  192.168.0.1 |МО| Адрес маршрутизатора |2.745|
|  3| 3.401 ms| 3.601 ms| 4.476 ms| 10.228.19.254 |МО| Gray IP |3.826|
|  4| 0.012 ms  | 8.348 ms  | 3.939 ms |  10.228.100.1 |МО| Gray IP | 4.099 |
|  5| 4.98 ms | 6.701 ms | 4.608 ms | 31.129.193.2 (ns3.khotkovo.net)  |МО| ООО ОТС |5.429|


```{r, echo=FALSE}
xt <- c(0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,210,220,230,240,250,260,270,280,290,300)
yh <- c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12,12.5,13,13.5,14,14.5,15)
x1 <- c(0.438,1.841,4.738,4.258,4.258,4.347,4.229,20.266,18.361,28.912,17.709,31.843,31.15,29.851,30.532)
y1 <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
x2 <- c(0.391,2.006,5.56,6.17,3.895,4.235,4.233,6.544,33.625,8.331)
y2 <- c(1,2,3,4,5,6,7,8,9,10)
x3 <- c(0.385,2.269,7.061,6.186,4.617,4.848,4.694,7.193,9.246,9.597,42.972,46.554,45.941,46.1)
y3 <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14)
x4 <- c(0.32,2.745,3.826,4.099,5.429)
y4 <- c(1,2,3,4,5)
plot(yh,xt, main = "Диаграмма RTT", xlab = "Шаг", ylab = "RTT",type = "n")
points(y1,x1,col = "red")
lines(y1,x1,col = "red")
points(y2,x2,col = "green")
lines(y2,x2,col = "green")
points(y3,x3,col = "blue")
lines(y3,x3,col = "blue")
points(y4,x4,col = "purple ")
lines(y4,x4,col = "purple ")
```

Цветовое обозначение:
  - Красный - Google Public DNS
  - Зеленый - Cloudflare DNS
  - Синий - OpenDNS
  - Фиолетовый - ОТС

### Оценка результата  
Больше всего времени потребовалось при обращении к OpenDNS, меньше всего - к ОТС.

### Вывод:  
Мы оценили скорость м кличество переходов между узлами до каждого из четырёх ns-серверов.